version: '3.8'

services:
  frpc-gateway:
    build:
      context: .
      dockerfile: Dockerfile.frpc
    container_name: frpc-gateway
    volumes:
      - ./data:/frp/data
      - ./config:/frp/config
    network_mode: host  # or bridge with correct forwarding